-- =============================================================================
-- ESQUEMA DE BANCO DE DADOS - PLATAFORMA LÓ (SUPABASE / POSTGRESQL)
-- =============================================================================
-- Este script atualiza a base existente e cria as novas tabelas para o Ló.
-- Pode ser executado com segurança no SQL Editor do Supabase.
-- =============================================================================

-- 1. TABELA DE PERFIS (profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Estudante Ló',
  course TEXT DEFAULT '',
  period TEXT DEFAULT '',
  target_gpa NUMERIC(5,2) DEFAULT 80.0,
  motivation_note TEXT DEFAULT 'Bora conquistar esse semestre! 🚀',
  theme TEXT DEFAULT 'dark',
  accent_color TEXT DEFAULT '#6366f1',
  avatar_data_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir colunas novas caso a tabela já existisse
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'motivation_note') THEN
    ALTER TABLE public.profiles ADD COLUMN motivation_note TEXT DEFAULT 'Bora conquistar esse semestre! 🚀';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'accent_color') THEN
    ALTER TABLE public.profiles ADD COLUMN accent_color TEXT DEFAULT '#6366f1';
  END IF;
END $$;

-- 2. TABELA DE MATÉRIAS (subjects)
CREATE TABLE IF NOT EXISTS public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  professor TEXT,
  target_grade NUMERIC(5,2) DEFAULT 80.0,
  color TEXT DEFAULT '#6366f1',
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir coluna description caso a tabela já existisse
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'subjects' AND column_name = 'description') THEN
    ALTER TABLE public.subjects ADD COLUMN description TEXT;
  END IF;
END $$;

-- 3. TABELA DE ATIVIDADES E PROVAS (activities)
CREATE TABLE IF NOT EXISTS public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type TEXT DEFAULT 'Prova',
  due_date DATE NOT NULL,
  weight NUMERIC(5,2) DEFAULT 25.0,
  max_grade NUMERIC(5,2) DEFAULT 100.0,
  obtained_grade NUMERIC(5,2),
  status TEXT DEFAULT 'Pendente',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABELA DE VINCULAÇÃO TELEGRAM (telegram_links)
CREATE TABLE IF NOT EXISTS public.telegram_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  chat_id BIGINT NOT NULL,
  username TEXT,
  notifications_enabled BOOLEAN DEFAULT true,
  reminder_hours TEXT DEFAULT '08:00,20:00',
  linked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABELA DE HISTÓRICO DE CONVERSAS DO BOT (bot_conversations)
CREATE TABLE IF NOT EXISTS public.bot_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  chat_id BIGINT NOT NULL,
  user_message TEXT NOT NULL,
  bot_response TEXT NOT NULL,
  context_type TEXT DEFAULT 'geral',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. TABELA DE CÓDIGOS TEMPORÁRIOS DE VINCULAÇÃO TELEGRAM (telegram_link_codes)
CREATE TABLE IF NOT EXISTS public.telegram_link_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =============================================================================
-- HABILITAR ROW LEVEL SECURITY (RLS)
-- =============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telegram_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telegram_link_codes ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS PROFILES
DROP POLICY IF EXISTS "Usuários podem ver seu próprio perfil" ON public.profiles;
CREATE POLICY "Usuários podem ver seu próprio perfil" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Usuários podem atualizar seu próprio perfil" ON public.profiles;
CREATE POLICY "Usuários podem atualizar seu próprio perfil" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Usuários podem inserir seu próprio perfil" ON public.profiles;
CREATE POLICY "Usuários podem inserir seu próprio perfil" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- POLÍTICAS SUBJECTS
DROP POLICY IF EXISTS "Usuários podem visualizar suas próprias matérias" ON public.subjects;
CREATE POLICY "Usuários podem visualizar suas próprias matérias" ON public.subjects FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuários podem inserir suas próprias matérias" ON public.subjects;
CREATE POLICY "Usuários podem inserir suas próprias matérias" ON public.subjects FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuários podem atualizar suas próprias matérias" ON public.subjects;
CREATE POLICY "Usuários podem atualizar suas próprias matérias" ON public.subjects FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuários podem excluir suas próprias matérias" ON public.subjects;
CREATE POLICY "Usuários podem excluir suas próprias matérias" ON public.subjects FOR DELETE USING (auth.uid() = user_id);

-- POLÍTICAS ACTIVITIES
DROP POLICY IF EXISTS "Usuários podem visualizar suas próprias atividades" ON public.activities;
CREATE POLICY "Usuários podem visualizar suas próprias atividades" ON public.activities FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuários podem inserir suas próprias atividades" ON public.activities;
CREATE POLICY "Usuários podem inserir suas próprias atividades" ON public.activities FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuários podem atualizar suas próprias atividades" ON public.activities;
CREATE POLICY "Usuários podem atualizar suas próprias atividades" ON public.activities FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuários podem excluir suas próprias atividades" ON public.activities;
CREATE POLICY "Usuários podem excluir suas próprias atividades" ON public.activities FOR DELETE USING (auth.uid() = user_id);

-- POLÍTICAS TELEGRAM_LINKS
DROP POLICY IF EXISTS "Usuários podem visualizar seu link do telegram" ON public.telegram_links;
CREATE POLICY "Usuários podem visualizar seu link do telegram" ON public.telegram_links FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuários podem gerenciar seu link do telegram" ON public.telegram_links;
CREATE POLICY "Usuários podem gerenciar seu link do telegram" ON public.telegram_links FOR ALL USING (auth.uid() = user_id);

-- POLÍTICAS BOT_CONVERSATIONS
DROP POLICY IF EXISTS "Usuários podem visualizar suas conversas" ON public.bot_conversations;
CREATE POLICY "Usuários podem visualizar suas conversas" ON public.bot_conversations FOR SELECT USING (auth.uid() = user_id);

-- POLÍTICAS TELEGRAM_LINK_CODES
DROP POLICY IF EXISTS "Usuários podem gerenciar seus códigos de link" ON public.telegram_link_codes;
CREATE POLICY "Usuários podem gerenciar seus códigos de link" ON public.telegram_link_codes FOR ALL USING (auth.uid() = user_id);

-- =============================================================================
-- TRIGGER: CRIAR PERFIL AUTOMÁTICO AO CADASTRAR NOVO USUÁRIO
-- =============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, course, period, target_gpa, motivation_note, theme, accent_color)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', 'Estudante Ló'),
    COALESCE(new.raw_user_meta_data->>'course', ''),
    COALESCE(new.raw_user_meta_data->>'period', ''),
    80.0,
    'Bora conquistar esse semestre! 🚀',
    'dark',
    '#6366f1'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
