-- =============================================================================
-- ESQUEMA DE BANCO DE DADOS - GESTÃO ACADÊMICA MONA (SUPABASE / POSTGRESQL)
-- =============================================================================
-- Instruções:
-- 1. Acesse o painel do seu projeto no Supabase (https://supabase.com)
-- 2. No menu lateral, clique em "SQL Editor"
-- 3. Cole todo este script e clique no botão "Run" (Executar)
-- =============================================================================

-- 1. TABELA DE PERFIS DE USUÁRIO (profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT DEFAULT 'Monalysa Delvivo Rocha',
  course TEXT DEFAULT 'Direito',
  period TEXT DEFAULT '7º Período',
  target_gpa NUMERIC(5,2) DEFAULT 85.0,
  love_note TEXT DEFAULT 'Bem vinda ao seu painel da facul, boa volta as aulas! ❤️',
  theme TEXT DEFAULT 'dark',
  avatar_data_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA DE MATÉRIAS (subjects)
CREATE TABLE IF NOT EXISTS public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  professor TEXT,
  target_grade NUMERIC(5,2) DEFAULT 85.0,
  color TEXT DEFAULT '#6366f1',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE ATIVIDADES E PROVAS (activities)
CREATE TABLE IF NOT EXISTS public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type TEXT DEFAULT 'Prova',
  due_date DATE NOT NULL,
  weight NUMERIC(5,2) DEFAULT 25.0,
  max_grade NUMERIC(5,2) DEFAULT 100.0,
  obtained_grade NUMERIC(5,2),
  status TEXT DEFAULT 'Pendente',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =============================================================================
-- HABILITAR ROW LEVEL SECURITY (RLS) - SEGURANÇA POR USUÁRIO
-- =============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS PARA PROFILES (Cada usuário só lê e edita o seu perfil)
CREATE POLICY "Usuários podem ver seu próprio perfil" 
  ON public.profiles FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Usuários podem atualizar seu próprio perfil" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

CREATE POLICY "Usuários podem inserir seu próprio perfil" 
  ON public.profiles FOR INSERT 
  WITH CHECK (auth.uid() = id);

-- POLÍTICAS PARA SUBJECTS (Cada usuário só gerencia suas matérias)
CREATE POLICY "Usuários podem visualizar suas próprias matérias" 
  ON public.subjects FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem inserir suas próprias matérias" 
  ON public.subjects FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem atualizar suas próprias matérias" 
  ON public.subjects FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem excluir suas próprias matérias" 
  ON public.subjects FOR DELETE 
  USING (auth.uid() = user_id);

-- POLÍTICAS PARA ACTIVITIES (Cada usuário só gerencia suas atividades)
CREATE POLICY "Usuários podem visualizar suas próprias atividades" 
  ON public.activities FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem inserir suas próprias atividades" 
  ON public.activities FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem atualizar suas próprias atividades" 
  ON public.activities FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem excluir suas próprias atividades" 
  ON public.activities FOR DELETE 
  USING (auth.uid() = user_id);

-- =============================================================================
-- TRIGGER AUTOMÁTICO: CRIAR PERFIL INICIAL AO CADASTRAR NOVO USUÁRIO
-- =============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, course, period, target_gpa, love_note, theme)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', 'Monalysa Delvivo Rocha'),
    'Direito',
    '7º Período',
    85.0,
    'Bem vinda ao seu painel da facul, boa volta as aulas! ❤️',
    'dark'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
